name: Currency
main: net.twasi.currency.Plugin
author: Twasi Team
description: The Twasi currency plugin
helpText: This plugin allows you to add a custom currency to your chatters.
version: 1.0

messageHandler: true

commands:
- currency

permissions:
- twasi.currency.streamer.operate